sudo: required
os: linux
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4

services:
  - docker

script:
  - docker version
  - docker build --no-cache --tag local/gamesvr-blackmesa --tag lacledeslan/gamesvr-blackmesa --build-arg BUILDNODE=TravisCI ./linux
  - docker run -it --rm local/gamesvr-blackmesa ./ll-tests/gamesvr-blackmesa.sh

notifications:
  slack:
    secure: BdZj4keWR8zR38bzVRaIC552XNy9GKOh/ySezO+J2rCGVdXDsgnql+G0QJWUkSG0ZQMx6s4GDMZfGeTHYe417m/oZJAksJwjAVHPndWHN2k5WWTz3lHTwbuVhLK28xqTLypUTXPk20ODlgAIWUJ6aXRr+S/Eqpyrk1zFY6kE0/NQKSlkRnhSf45taTGVxMkh37dMcp3jkonvolHoWhaGugSlJ1G8AfAYWZGdaWRtYJ/6QaPesRyHrqGaiQaSc1Jdjz4PmfgIGqxXr0+PCdz8aUtAh4qXG3RlPOaShgcAhKLURpmCjInjGhnoDNPnEkiXsTlnzuJbbSZ3ZmyMjcLYFdt3nKIdp7AB2IFx0VabJbrFOvz5yawGOvT2fSWUk3Oya2wd3XeHDlsPns5iIWYP8K7stfonkRsT0mh6OUzS/iVmIX61aLKZsFpUVLfKOCAr2nKe3zf6QuyI9XB7FkM+8m9k9+2pg+1v96KZb34xnLkieTV7pXbxW3f5vDIuhaKzYfnDIGpRxuXAGiBu6GiRK/YzXA/jHjXQpYo4vJ0Gl5Q+eUB4L0A21NzI4Pu/o0kp2pg1QoouH0PlVzWHq35B2VFkYK9n6jV915snR3Wv6BgdM4Gf9PkVd9SaKiD4LufeF/6m7ApEmHsUoLRGmaC2G4EsxBY4QuGh2jaP6usBFzs=

before_deploy:
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS";
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-blackmesa
  on:
    branch: master
after_deploy:
 - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-blackmesa/$MICROBADGER_TOKEN
 - sh ./.travis/trigger-travis.sh LacledesLAN gamesvr-blackmesa-freeplay $TRAVIS_ACCESS_TOKEN
